### PR TITLE
Leader election

### LINKED ISSUE #10: Leader election features
Implement equivalents to these methods in the [Go client](http://godoc.org/github.com/flynn/go-discoverd):
- [x] RegisterAndStandby
- [x] ServiceSet.Leader
- [x] ServiceSet.Leaders

### PR DESCRIPTION
**Pull request by lmars**
I had some fun with race conditions on this one as Celluloid doesn't play nice when you pass Procs around (see [here](https://github.com/flynn/discoverd-ruby/blob/leader-election/lib/discover.rb#L256))

Closes #10.

### CODE REVIEW

**Comment by titanous** [comment]
Travis looks broken?

**Comment by titanous** [comment]
Yeah, I ended up spending a couple hours on [this one](https://github.com/flynn/discoverd-ruby/blob/9c6f5f94daefa5f17055760bdfac8b031428dc57/lib/discover.rb#L149-L151).

**Comment by titanous** [comment]
LGTM as soon as Travis is green.

**Comment by lmars** [comment]
@titanous yes that exclusive lock didn't work as I expected, so I've updated it to use a Condition instead (see [here](https://github.com/flynn/discoverd-ruby/blob/leader-election/lib/discover.rb#L260)).

All passing now so good to merge?

**Pull request merged**
